from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(740, 520)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.path_input = QTextEdit(self.centralwidget)
        self.path_input.setObjectName(u"path_input")
        self.path_input.setGeometry(QRect(10, 420, 240, 30))
        font = QFont()
        font.setPointSize(10)
        self.path_input.setFont(font)
        self.count_input = QSpinBox(self.centralwidget)
        self.count_input.setObjectName(u"count_input")
        self.count_input.setGeometry(QRect(155, 460, 130, 30))
        self.count_input.setFont(font)
        self.count_input.setMaximum(100000)
        self.b_start = QPushButton(self.centralwidget)
        self.b_start.setObjectName(u"b_start")
        self.b_start.setGeometry(QRect(10, 460, 130, 30))
        self.b_start.setFont(font)
        self.b_path = QPushButton(self.centralwidget)
        self.b_path.setObjectName(u"b_path")
        self.b_path.setGeometry(QRect(250, 420, 35, 30))
        self.b_delete = QPushButton(self.centralwidget)
        self.b_delete.setObjectName(u"b_delete")
        self.b_delete.setGeometry(QRect(10, 380, 85, 30))
        self.b_scr = QPushButton(self.centralwidget)
        self.b_scr.setObjectName(u"b_scr")
        self.b_scr.setGeometry(QRect(105, 380, 85, 30))
        self.b_fix = QPushButton(self.centralwidget)
        self.b_fix.setObjectName(u"b_fix")
        self.b_fix.setGeometry(QRect(200, 380, 85, 30))
        self.mod_list = QListWidget(self.centralwidget)
        self.mod_list.setObjectName(u"mod_list")
        self.mod_list.setGeometry(QRect(10, 10, 275, 360))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(290, 10, 221, 360))
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(u"")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.density_default = QDoubleSpinBox(self.groupBox)
        self.density_default.setObjectName(u"density_default")
        self.density_default.setGeometry(QRect(10, 20, 101, 21))
        self.density_default.setMaximum(10000000000.000000000000000)
        self.young_default = QDoubleSpinBox(self.groupBox)
        self.young_default.setObjectName(u"young_default")
        self.young_default.setGeometry(QRect(10, 50, 101, 21))
        self.young_default.setMaximum(10000000000.000000000000000)
        self.poisson_default = QDoubleSpinBox(self.groupBox)
        self.poisson_default.setObjectName(u"poisson_default")
        self.poisson_default.setGeometry(QRect(10, 80, 101, 21))
        self.poisson_default.setMaximum(10000000000.000000000000000)
        self.density_non_default = QDoubleSpinBox(self.groupBox)
        self.density_non_default.setObjectName(u"density_non_default")
        self.density_non_default.setGeometry(QRect(10, 130, 101, 21))
        self.density_non_default.setMaximum(10000000000.000000000000000)
        self.young_non_default = QDoubleSpinBox(self.groupBox)
        self.young_non_default.setObjectName(u"young_non_default")
        self.young_non_default.setGeometry(QRect(10, 160, 101, 21))
        self.young_non_default.setMaximum(10000000000.000000000000000)
        self.poisson_non_default = QDoubleSpinBox(self.groupBox)
        self.poisson_non_default.setObjectName(u"poisson_non_default")
        self.poisson_non_default.setGeometry(QRect(10, 190, 101, 21))
        self.poisson_non_default.setMaximum(10000000000.000000000000000)
        self.yield_non_default = QDoubleSpinBox(self.groupBox)
        self.yield_non_default.setObjectName(u"yield_non_default")
        self.yield_non_default.setGeometry(QRect(10, 220, 101, 21))
        self.yield_non_default.setMaximum(10000000000.000000000000000)
        self.aof_non_default = QDoubleSpinBox(self.groupBox)
        self.aof_non_default.setObjectName(u"aof_non_default")
        self.aof_non_default.setGeometry(QRect(10, 250, 101, 21))
        self.aof_non_default.setMaximum(10000000000.000000000000000)
        self.cs_non_default = QDoubleSpinBox(self.groupBox)
        self.cs_non_default.setObjectName(u"cs_non_default")
        self.cs_non_default.setGeometry(QRect(10, 280, 101, 21))
        self.cs_non_default.setMaximum(10000000000.000000000000000)
        self.rb_rein = QRadioButton(self.groupBox)
        self.rb_rein.setObjectName(u"rb_rein")
        self.rb_rein.setGeometry(QRect(10, 105, 131, 20))
        self.b_material = QPushButton(self.groupBox)
        self.b_material.setObjectName(u"b_material")
        self.b_material.setGeometry(QRect(10, 310, 101, 30))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 20, 90, 20))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 50, 90, 20))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(120, 80, 90, 20))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(120, 130, 90, 20))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(120, 160, 90, 20))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(120, 190, 90, 20))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(120, 220, 90, 20))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(120, 250, 90, 20))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(120, 280, 90, 20))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(510, 10, 220, 360))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(u"")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.scar_prob = QDoubleSpinBox(self.groupBox_2)
        self.scar_prob.setObjectName(u"scar_prob")
        self.scar_prob.setGeometry(QRect(10, 50, 101, 21))
        self.scar_prob.setMaximum(100.000000000000000)
        self.out_disk_prob = QDoubleSpinBox(self.groupBox_2)
        self.out_disk_prob.setObjectName(u"out_disk_prob")
        self.out_disk_prob.setGeometry(QRect(10, 80, 101, 21))
        self.out_disk_prob.setMaximum(100.000000000000000)
        self.net_value = QDoubleSpinBox(self.groupBox_2)
        self.net_value.setObjectName(u"net_value")
        self.net_value.setGeometry(QRect(10, 20, 101, 21))
        self.net_value.setMaximum(1000000.000000000000000)
        self.b_scr_prob = QPushButton(self.groupBox_2)
        self.b_scr_prob.setObjectName(u"b_scr_prob")
        self.b_scr_prob.setGeometry(QRect(120, 50, 90, 20))
        self.b_out_disc_prob = QPushButton(self.groupBox_2)
        self.b_out_disc_prob.setObjectName(u"b_out_disc_prob")
        self.b_out_disc_prob.setGeometry(QRect(120, 80, 90, 20))
        self.b_net = QPushButton(self.groupBox_2)
        self.b_net.setObjectName(u"b_net")
        self.b_net.setGeometry(QRect(120, 20, 90, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.b_start.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.b_path.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.b_delete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.b_scr.setText(QCoreApplication.translate("MainWindow", u"Add scr", None))
        self.b_fix.setText(QCoreApplication.translate("MainWindow", u"Add fix", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Material", None))
        self.rb_rein.setText(QCoreApplication.translate("MainWindow", u"Use reinforcement", None))
        self.b_material.setText(QCoreApplication.translate("MainWindow", u"Add mat", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Density", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Young's mod", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Poisson ratio", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Density", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Young's mod", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Poisson ratio", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Yield stress", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"AOF", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"CS", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"mod probabilities", None))
        self.b_scr_prob.setText(QCoreApplication.translate("MainWindow", u"Scr", None))
        self.b_out_disc_prob.setText(QCoreApplication.translate("MainWindow", u"Out disc", None))
        self.b_net.setText(QCoreApplication.translate("MainWindow", u"Net", None))

MainWindow = QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()